# Site settings
title: rtrollebo.github.io
description: "Notes on mathematical analysis, physics and software engineering"
baseurl: ""
url: "github.com/rtrollebo"
github_username: rtrollebo
facebook_username: robert.trollebo
linkedin_username: rtrollebo

# Build settings
markdown: kramdown
permalink: /notes/:year/:month/:day/:title/
