# Site settings
title: rtrollebo.github.io
description: "I am a M.Sc. with interests in mathematical analysis, physics and computer science"
baseurl: ""
url: "github.com/rtrollebo"
skype_username: trolleboe
github_username: rtrollebo
facebook_username: robert.trollebo
linkedin_username: rtrollebo

# Build settings
markdown: kramdown
permalink: /notes/:year/:month/:day/:title/
